defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

# Mode
model_resume : false
model_resume_name: exp_220110_tvcomm_qut_demand/latest_model.tar

## Models
model : demucs
demucs :
  chin: 1
  chout: 1
  hidden: 48
  max_hidden: 10000
  causal: true
  glu: true
  depth: 5
  kernel_size: 8
  stride: 4
  normalize: true
  resample: 4
  growth: 2
  rescale: 0.1

# Dataset Augmentation
remix: false   # remix noise and clean
bandmask: 0   # drop at most this fraction of freqs in mel scale
shift: 0    # random shift, number of samples
shift_same: false   # shift noise and clean by the same amount
revecho: 0  # add reverb like augment

# Optimizer
optim : adam
lr : 8e-4
# lr : 3e-4
# lr : 1e-3 ### too high
beta2 : 0.999
loss : l1
# epoch : 50
epoch : 150
batch_size : 32
stft_loss: True
stft_sc_factor: .5
stft_mag_factor: .5

# training config
device : cuda:2
num_workers : 1
train_num_print : 5
valid_num_print : 5
sample_rate : 16000
data_len_limit : 8
train_dataset_len : full #full = 109,086개
valid_dataset_len : full #full = 1,102개

# Hydra config
hydra:
  run:
    dir: ./outputs/exp_${hydra.job.override_dirname}
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        # Remove all paths, as the / in them would mess up things
        # Remove params that would not impact the training itself
        # Remove all slurm and submit params.
        # This is ugly I know...
        exclude_keys: [
          'hydra.job_logging.handles.file.filename',
          'dset.train', 'dset.valid', 'dset.test', 'dset.noisy_json', 'dset.noisy_dir',
          'num_prints', 'continue_from',
          'device', 'num_workers', 'print_freq', 'restart', 'verbose',
          'log', 'ddp', 'ddp_backend', 'rendezvous_file', 'rank', 'world_size']
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr

  hydra_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr
